import os
import json
from groq import Groq
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

# Mock or real LLM client
class LLMClient:
    """
    Client wrapper for interacting with the Groq API or falling back to mock responses.

    Attributes:
        api_key (str): The Groq API key used for authentication.
        client (Groq or None): The initialized Groq client instance.
        use_mock (bool): True if dummy fallback mode is active due to a missing or invalid API key.
    """
    def __init__(self):
        """
        Initializes the LLMClient instance by checking for GROQ_API_KEY environment variables.
        """
        self.api_key = os.environ.get("GROQ_API_KEY", "dummy_key")
        try:
            self.client = Groq(api_key=self.api_key)
            self.use_mock = self.api_key == "dummy_key"
        except Exception:
            self.use_mock = True

    def generate(self, system_prompt: str, user_prompt: str, require_json: bool = False) -> str:
        """
        Generates content from the LLM based on system and user prompts.

        Args:
            system_prompt (str): Instructions providing context and constraints to the LLM.
            user_prompt (str): The actual prompt content/question from the user or agent.
            require_json (bool, optional): Whether to enforce JSON-formatted output from the model.
                Defaults to False.

        Returns:
            str: The text content generated by the model, or a structured JSON string if requested.
        """
        if self.use_mock:
            # Fallback mock responses if no API key is provided
            if require_json:
                return json.dumps({"response": "Mock LLM JSON Response", "business_insights": "The data shows potential mock trends."})
            return "This is a mock LLM response. Please set GROQ_API_KEY for live inference."
            
        try:
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
            response = self.client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=messages,
                response_format={"type": "json_object"} if require_json else None,
                temperature=0.3
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            if require_json:
                return json.dumps({"error": str(e), "business_insights": "Fallback: Error calling LLM."})
            return f"Error calling LLM: {str(e)}"
