from pydantic import BaseModel
from typing import List, Dict, Any

class ChartData(BaseModel):
    """
    Structured representation of a generated chart for the frontend to render.

    Attributes:
        type (str): The chart type (e.g., 'bar', 'line', 'scatter').
        title (str): The business-friendly title of the chart.
        analysis_type (str): The logical classification of the analysis (e.g., 'comparison', 'trend').
        figure (Dict[str, Any]): The JSON structure defining the chart (e.g., Plotly layout and data).
    """
    type: str
    title: str
    analysis_type: str
    figure: Dict[str, Any]

class DatasetSummary(BaseModel):
    """
    A concise statistical summary of the dataset's structural shape and column types.

    Attributes:
        row_count (int): The total number of rows.
        column_count (int): The total number of columns.
        numeric_columns (List[str]): A list of numeric column names.
        categorical_columns (List[str]): A list of categorical column names.
        datetime_columns (List[str]): A list of datetime column names.
    """
    row_count: int
    column_count: int
    numeric_columns: List[str]
    categorical_columns: List[str]
    datetime_columns: List[str]

class Module3Result(BaseModel):
    """
    The final output generated by the Module 3 Analysis Pipeline.

    Attributes:
        charts (List[ChartData]): A collection of visual chart definitions.
        insights (List[str]): Data-driven bullet point insights describing anomalies or trends.
        explanations (str): A concise, human-readable summary of the overall business impact.
        analysis_plan (List[str]): The sequence of analysis queries or steps planned by the agent.
        stats (Dict[str, Any]): The raw calculated statistics (distributions, correlations, etc.).
        chat_response (str): The conversational answer to the user's input query.
        confidence_score (float): The calculated confidence metric of the generated insights.
        rag_context (str): The raw text context retrieved and utilized by the RAG engine.
        dataset_summary (DatasetSummary): The overarching structural summary of the active dataset.
    """
    charts: List[ChartData]
    insights: List[str]
    explanations: str
    analysis_plan: List[str]
    stats: Dict[str, Any]
    chat_response: str
    confidence_score: float
    rag_context: str
    dataset_summary: DatasetSummary
