from fastapi import APIRouter, HTTPException
from ..schemas import AnalyzeRequest
from .upload import datasets
from ...core.pipeline import run_module3
import pandas as pd

router = APIRouter()

analysis_results = {}

@router.post("/analyze")
async def analyze_dataset(req: AnalyzeRequest):
    """
    Analyzes a loaded dataset based on the user's specific query.

    Mock outputs from Module 1 and Module 2 are prepared and passed to the
    Module 3 core pipeline along with the dataset and the user query.

    Args:
        req (AnalyzeRequest): The request payload containing dataset_id and optional query.

    Returns:
        dict: The final analysis result generated by the Module 3 pipeline, including insights,
              suggested plans, charts, statistics, and validation details.

    Raises:
        HTTPException: If the specified dataset_id does not exist in memory.
    """
    dataset_id = req.dataset_id
    if dataset_id not in datasets:
        raise HTTPException(status_code=404, detail="Dataset not found")
        
    df = datasets[dataset_id]
    
    # Mock module1 and module2 outputs
    module1_output = {
        "dataset_name": "Uploaded Dataset",
        "dataset_summary": {
            "description": "Dataset description",
            "numeric_columns": df.select_dtypes(include="number").columns.tolist(),
            "categorical_columns": df.select_dtypes(include="object").columns.tolist(),
            "datetime_columns": df.select_dtypes(include="datetime").columns.tolist(),
            "column_meanings": {col: "A column" for col in df.columns}
        }
    }
    module2_output = {}
    
    result = run_module3(module1_output, module2_output, df, user_query=req.query)
    analysis_results[dataset_id] = result
    
    return result
