import json
from typing import Dict, Any, List
from utils.llm_client import LLMClient

class ChatAgent:
    """
    Conversational assistant engine that allows interactive business intelligence questioning
    directly against the output metrics of other forecasting/prediction engines.
    """
    def __init__(self):
        """
        Initializes ChatAgent with the central LLM client utility.
        """
        self.llm = LLMClient()
        
    def chat(self, user_message: str, context_data: Dict[str, Any]) -> str:
        """
        Processes a user question alongside multi-engine analytical context to generate business replies.

        Args:
            user_message (str): Natural language inquiry from the user.
            context_data (Dict[str, Any]): Structured workspace state detailing predictions, forecasts, RCA, and risk.

        Returns:
            str: Explanatory conversational answer generated by the model.
        """
        system_prompt = (
            "You are a 'Future Intelligence Engine' Conversational Assistant. "
            "Your goal is to answer questions from business stakeholders about the future insights, "
            "predictions, forecasts, root causes, and strategic recommendations generated by the AI platform. "
            "Use the provided context to answer the user's question in a clear, non-technical, and business-focused manner. "
            "Do not talk about ML metrics like SHAP, MSE, or logloss unless explicitly asked. "
            "Focus on 'What will happen?', 'Why will it happen?', and 'What should we do about it?'"
        )
        
        # Summarize context to avoid exceeding token limits
        safe_context = {
            "prediction_summary": context_data.get("prediction", {}).get("confidence", {}),
            "rca_summary": context_data.get("rca", {}).get("explanation", ""),
            "recommendation_summary": [
                r.get("action") for r in context_data.get("recommendation", {}).get("recommendations", [])[:3]
            ],
            "risk_summary": context_data.get("risk", {}).get("risk_score", 0.0),
            "executive_decision": context_data.get("decision", {}).get("executive_summary", ""),
            "action_plan": context_data.get("decision", {}).get("action_plan", [])
        }
        
        user_prompt = f"Context from the AI platform:\n{json.dumps(safe_context, indent=2)}\n\nUser Question: {user_message}\n\nPlease provide a helpful business-oriented response."
        
        try:
            return self.llm.generate(system_prompt, user_prompt, require_json=False)
        except Exception as e:
            return f"I am unable to process the question at the moment. Error: {str(e)}"
